### ISSUE TITLE
Missing required parameter "id"

### ISSUE THREAD

**Issue by filsh** [bupy7/yii2-config#3]
Exception 'yii\base\InvalidConfigException' with message 'Missing required parameter "id" when instantiating "bupy7\config\Module".'

in /var/www/html/vendor/yiisoft/yii2/di/Container.php:451

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->resolveDependencies(Array, Object(ReflectionClass))
#1 /var/www/html/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->build('bupy7\config\Mo...', Array, Array)
#2 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(340): yii\di\Container->get('bupy7\config\Mo...', Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Application.php(288): yii\BaseYii::createObject('bupy7\config\Mo...')
#4 /var/www/html/vendor/yiisoft/yii2/base/Application.php(267): yii\base\Application->bootstrap()
#5 /var/www/html/vendor/yiisoft/yii2/console/Application.php(120): yii\base\Application->init()
#6 /var/www/html/vendor/yiisoft/yii2/base/Object.php(107): yii\console\Application->init()
#7 /var/www/html/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object->__construct(Array)
#8 /var/www/html/vendor/yiisoft/yii2/console/Application.php(85): yii\base\Application->__construct(Array)
#9 /var/www/html/yii(30): yii\console\Application->__construct(Array)
#10 {main}

**Comment by bupy7** [comment]
One moment. Wait version 1.0.2.

**Comment by bupy7** [comment]
Fixed.

**Comment by filsh** [comment]
thanks
